language: node_js
node_js:
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs
after_success:
  - npm run-script coveralls
notifications:
  slack:
    secure: mFN1Z9UjqoBPLEL2RtJ5SgwG+S9upzgxMHikpL+BaI7pBNAujIi09VWefZ20x91hFUUHVdPRVsQQOC8sPOib3TQcymAZAnzrBFvLYrIvHkhXDtoKE79VnxSIOj2BcjJAKemyCGC5dQtktLch4uQT1Dl3ZZPb7nNviJPPHS7CUuO7Rp3R+s9m9N3ir0eriH5/7EPJXG63CrYJmEtR1qtS7x7XHA0s+xrmzweX503oSav3+79RQYFnoFEAdBBk/G7Ymy4DLM385UcNBXwE+ibzusTKN/HPgkL18HTwh5eos+Tkctb/ToPVUhvI9bL3J1MYX65Fq94phDcIivUwtuCjxo1AHj0yOLJ9U3WPBmc7dEcch8z1IYIf8dygL7sEXo/15HLdNEkiuXNBceZF9/vW4S9STgSPwo1rfjd2EK6dv72DkJoX2TsIXXN0itk0L1Wxjsk5q/kZZ0LQ3V7gUSpVmjKEB4vIYjgJfqFu+AqRVVqYqjSruHDpmMdX8NvSyXH7ClQk+KUS7Pv02947CE3HgQM0hgaZoOxysYyzW7LJeIASbPL23ZG2jWNwF5Pnl5Pil42ksWJ70uQyDQOG1iEyWtKkxGY0c46FugTZLwhN6lMEZAjam3V3yEBWaGc/wGNvhJGLcVh98Ut6byxTwmijLpIWn+QCgFtjdepIcVr3FlI=
