version: "3.7"
services:
  app:
    build: .
    env_file: .env
    command: bin/hubot -n Hubot --adapter slack
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    driver: local
