version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.12
    steps:
      - checkout

      - restore_cache:
          key: hubot-script-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: hubot-script-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Run test
          command: yarn test
      - run:
          name: Measure coverage
          command: |
            yarn run coverage
            cat coverage/lcov.info | "$(npm bin)/coveralls"

  update:
    docker:
      - image: circleci/node:8.9
        environment:
          FORK_USERNAME: yulii-bot
          UPDATE_LOCK_FILE: yarn.lock
    steps:
      - run:
          name: Checkout code
          command: |
            git clone -b master --depth 1 https://${FORK_REPO_TOKEN}@github.com/yulii-bot/hubot-scripts.git .
            git remote add upstream https://github.com/yulii/hubot-scripts.git
            git fetch upstream
            git checkout master
            git merge upstream/master
      - run:
          name: Update dependencies
          command: yarn upgrade
      - run:
          name: Commit auto update file
          command: |
            test -z "$(git status -s yarn.lock 2> /dev/null)" && echo 'No update.' && exit 0
            BRANCH="bundle-update-$(sha1sum yarn.lock | cut -d' ' -f1)"
            test -n "$(git ls-remote origin ${BRANCH} 2> /dev/null)" && echo 'Already committed.' && exit 0
            git config --local user.email 'yuliinfo+bot@gmail.com'
            git config --local user.name 'yulii-bot'
            git add yarn.lock
            git commit -m 'Yarn upgrade'
            git branch -M ${BRANCH}
            git push origin ${BRANCH}
      - run:
          name: Send auto update pull request
          command: |
            BRANCH="bundle-update-$(sha1sum yarn.lock | cut -d' ' -f1)"
            test -z "$(git ls-remote origin ${BRANCH} 2> /dev/null)" && echo "Update branch not found." && exit 0
            git fetch origin ${BRANCH}
            test -z "$(git diff upstream/master...FETCH_HEAD)" && echo "No changes." && exit 0
            curl -H "Authorization: token ${FORK_REPO_TOKEN}" \
                 -X POST -H "Content-Type: application/json" \
                 -d "{ \"title\": \"Yarn upgrade\", \"body\": \"Auto update pull request!\", \"head\": \"yulii-bot:${BRANCH}\", \"base\": \"master\" }" \
                 "https://api.github.com/repos/yulii/hubot-scripts/pulls" \
                 | tee /tmp/create-pull-request.log.json
            test -n "$(cat /tmp/create-pull-request.log.json | jq -r 'select(.errors == null)')"
workflows:
  version: 2
  build_and_update:
    jobs:
      - build
      - update:
          requires:
            - build
          filters:
            branches:
              only: master
