version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.2
    steps:
      - checkout

      - restore_cache:
          key: hubot-script-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: hubot-script-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Run test
          command: yarn test
      - run:
          name: Measure coverage
          command: |
            yarn run coverage
            cat coverage/lcov.info | "$(npm bin)/coveralls"

  update:
    docker:
      - image: circleci/node:9.2
        environment:
          FORK_USERNAME: yulii-bot
          UPDATE_LOCK_FILE: yarn.lock
    steps:
      - run:
          name: Checkout code
          command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/yulii/fork-update/master/checkout)"
      - run:
          name: Update dependencies
          command: yarn upgrade
      - run:
          name: Send auto update pull request
          command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/yulii/fork-update/master/pull-request)"

workflows:
  version: 2
  build_and_update:
    jobs:
      - build
      - update:
          requires:
            - build
          filters:
            branches:
              only: master
